### ISSUE TITLE
Error: The requested accessory '" + name + "' was not registered by any plugin.

### ISSUE THREAD

**Issue by emilagervigstarup** [YinHangCode/homebridge-raspberrypi-temperature#5]
**Error:**
`
[2018-5-17 15:20:46] Loading 1 accessories...
/usr/lib/node_modules/homebridge/lib/api.js:64
      throw new Error("The requested accessory '" + name + "' was not registered by any plugin.");
      ^

Error: The requested accessory 'RaspberryPiTemperature' was not registered by any plugin.
    at API.accessory (/usr/lib/node_modules/homebridge/lib/api.js:64:13)
    at Server._loadAccessories (/usr/lib/node_modules/homebridge/lib/server.js:264:42)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:86:38)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
`

**Config file:**
`{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },

    "description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",
    "accessories": [
                {
                        "accessory": "RaspberryPiTemperature",
                        "name": "RaspberryPi CPU Temperature",
                        "updateInterval": 1000
                }
        ],

    "platforms": [
    ]
}`

**Comment by emilagervigstarup** [comment]
I just needed to install with -g:
sudo npm install -g homebridge-raspberrypi-temperature
then it works :)

**Comment by LegendaryWiz** [comment]
Had the exact same issue as u , the new command worked , thank you .
